const PENSUMS_DATA = {
    "mecanica": {
        "NOMBRE": "Ingeniería Mecánica", "TOTAL_CREDITOS_CARRERA": 193,
        "pensum": [
            { "id": 1, "nombre": 'Introducción A La Ingeniería', "codigo": '0012', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 2, "nombre": 'Lengua Y Comunicación', "codigo": '0183', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 3, "nombre": 'Cálculo I', "codigo": '0251', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 4, "nombre": 'Física General I', "codigo": '0331', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 5, "nombre": 'Geometría Descriptiva I', "codigo": '0551', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 6, "nombre": 'Inglés Instrumental De Mecánica', "codigo": '0108', "creditos": 2, "semestre": 2, "prelaciones": [{"tipo": 'creditos', "valor": 12}] },
            { "id": 7, "nombre": 'Algebra Lineal Y Geometría', "codigo": '0250', "creditos": 4, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 8, "nombre": 'Cálculo II', "codigo": '0252', "creditos": 5, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 9, "nombre": 'Química General I', "codigo": '0441', "creditos": 5, "semestre": 2, "prelaciones": [] },
            { "id": 10, "nombre": 'Dibujo y Diseño en Ingeniería', "codigo": '4811', "creditos": 3, "semestre": 2, "prelaciones": ['0551'] },
            { "id": 11, "nombre": 'Redacción De Informes De Mecánica', "codigo": '0167', "creditos": 3, "semestre": 3, "prelaciones": ['0183', {"tipo": 'creditos', "valor": 30}] },
            { "id": 12, "nombre": 'Cálculo III', "codigo": '0253', "creditos": 5, "semestre": 3, "prelaciones": ['0252'] },
            { "id": 13, "nombre": 'Física General II', "codigo": '0332', "creditos": 5, "semestre": 3, "prelaciones": ['0251', '0331'] },
            { "id": 14, "nombre": 'Mecánica I', "codigo": '0607', "creditos": 4, "semestre": 3, "prelaciones": ['0252', '0331'] },
            { "id": 15, "nombre": 'Programación', "codigo": '0790', "creditos": 4, "semestre": 3, "prelaciones": ['0250'] },
            { "id": 16, "nombre": 'Ecuaciones Diferenciales', "codigo": '0256', "creditos": 5, "semestre": 4, "prelaciones": ['0250', '0253'] },
            { "id": 17, "nombre": 'Cálculo IV', "codigo": '0270', "creditos": 4, "semestre": 4, "prelaciones": ['0250', '0253'] },
            { "id": 18, "nombre": 'Laboratorio Integrado De Física', "codigo": '0337', "creditos": 3, "semestre": 4, "prelaciones": ['0332'] },
            { "id": 19, "nombre": 'Mecánica II', "codigo": '0608', "creditos": 4, "semestre": 4, "prelaciones": ['0250', '0253', '0607'] },
            { "id": 20, "nombre": 'Materiales Para Ingeniería', "codigo": '4911', "creditos": 4, "semestre": 4, "prelaciones": ['0253', '0441'] },
            { "id": 21, "nombre": 'Cálculo Numérico', "codigo": '0258', "creditos": 4, "semestre": 5, "prelaciones": ['0256', '0790'] },
            { "id": 22, "nombre": 'Termodinámica I', "codigo": '4711', "creditos": 4, "semestre": 5, "prelaciones": ['0256', '0270'] },
            { "id": 23, "nombre": 'Mecánica De Fluidos I', "codigo": '4721', "creditos": 4, "semestre": 5, "prelaciones": ['0256', '0608', '0270'] },
            { "id": 24, "nombre": 'Mecánica De Sólidos I', "codigo": '4821', "creditos": 4, "semestre": 5, "prelaciones": ['0256', '0607'] },
            { "id": 25, "nombre": 'Mecánica De Máquinas', "codigo": '4831', "creditos": 4, "semestre": 5, "prelaciones": ['0608'] },
            { "id": 26, "nombre": 'Ingeniería Eléctrica I', "codigo": '4611', "creditos": 4, "semestre": 6, "prelaciones": ['0258', '0270', '0332'] },
            { "id": 27, "nombre": 'Termodinámica II', "codigo": '4712', "creditos": 4, "semestre": 6, "prelaciones": ['0441', '4711'] },
            { "id": 28, "nombre": 'Mecánica De Fluidos II', "codigo": '4722', "creditos": 4, "semestre": 6, "prelaciones": ['4721'] },
            { "id": 29, "nombre": 'Mecánica De Sólidos II', "codigo": '4822', "creditos": 4, "semestre": 6, "prelaciones": ['4821'] },
            { "id": 30, "nombre": 'Vibraciones Mecánicas', "codigo": '4832', "creditos": 4, "semestre": 6, "prelaciones": ['4821', '4831'] },
            { "id": 31, "nombre": 'Controles Automáticos', "codigo": '4612', "creditos": 4, "semestre": 7, "prelaciones": ['4611', '4832'] },
            { "id": 32, "nombre": 'Transferencia De Calor', "codigo": '4731', "creditos": 5, "semestre": 7, "prelaciones": ['0258', '4712', '4722'] },
            { "id": 33, "nombre": 'Turbomáquinas', "codigo": '4741', "creditos": 5, "semestre": 7, "prelaciones": ['4712', '4722'] },
            { "id": 34, "nombre": 'Diseño De Máquinas I', "codigo": '4812', "creditos": 4, "semestre": 7, "prelaciones": ['4822'] },
            { "id": 35, "nombre": 'Procesos De Fabricación I', "codigo": '4921', "creditos": 4, "semestre": 7, "prelaciones": ['4811', '4911'] },
            { "id": 36, "nombre": 'Instrumentación', "codigo": '4613', "creditos": 4, "semestre": 8, "prelaciones": ['4612', '4721'] },
            { "id": 37, "nombre": 'Conversión De Energía', "codigo": '4751', "creditos": 5, "semestre": 8, "prelaciones": ['4731', '4741'] },
            { "id": 38, "nombre": 'Diseño De Máquinas II', "codigo": '4813', "creditos": 4, "semestre": 8, "prelaciones": ['4812'] },
            { "id": 39, "nombre": 'Procesos De Fabricación II', "codigo": '4922', "creditos": 4, "semestre": 8, "prelaciones": ['4921'] },
            { "id": 40, "nombre": 'Producción I', "codigo": '4931', "creditos": 3, "semestre": 8, "prelaciones": ['4921'] },
            { "id": 41, "nombre": 'Diseño Conceptual', "codigo": '4814', "creditos": 4, "semestre": 9, "prelaciones": ['4813', '4922'] },
            { "id": 42, "nombre": 'Producción II', "codigo": '4932', "creditos": 3, "semestre": 9, "prelaciones": ['4931'] },
            { "id": 43, "nombre": 'Electiva', "codigo": 'ELV-1', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 44, "nombre": 'Electiva', "codigo": 'ELV-2', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 45, "nombre": 'Electiva', "codigo": 'ELV-3', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 46, "nombre": 'Electiva Humanística', "codigo": 'ELH-1', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 47, "nombre": 'Trabajo Especial De Grado', "codigo": '4501', "creditos": 8, "semestre": 10, "prelaciones": [{"tipo": 'creditos', "valor": 170}] },
            { "id": 48, "nombre": 'Electiva', "codigo": 'ELV-4', "creditos": 3, "semestre": 10, "prelaciones": [] },
            { "id": 49, "nombre": 'Electiva Humanística', "codigo": 'ELH-2', "creditos": 3, "semestre": 10, "prelaciones": [] }
        ]
    },
    "civil": {
        "NOMBRE": "Ingeniería Civil", "TOTAL_CREDITOS_CARRERA": 201,
        "pensum": [
            { "id": 101, "nombre": 'Cálculo I', "codigo": '0251', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 102, "nombre": 'Física General I', "codigo": '0331', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 103, "nombre": 'Geometría Descriptiva I', "codigo": '0551', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 104, "nombre": 'Introducción a la Ingeniería', "codigo": '0012', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 105, "nombre": 'Lengua y Comunicación', "codigo": '0183', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 106, "nombre": 'Cálculo II', "codigo": '0252', "creditos": 5, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 107, "nombre": 'Laboratorio de Física General', "codigo": '0334', "creditos": 1, "semestre": 2, "prelaciones": ['0331'] },
            { "id": 108, "nombre": 'Geometría Descriptiva II', "codigo": '0552', "creditos": 4, "semestre": 2, "prelaciones": ['0551'] },
            { "id": 109, "nombre": 'Tópicos de Física General', "codigo": '0333', "creditos": 4, "semestre": 2, "prelaciones": ['0331', '0251'] },
            { "id": 110, "nombre": 'Algebra Lineal y Geometría', "codigo": '0250', "creditos": 4, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 111, "nombre": 'Electiva Socio-Humanística', "codigo": 'ESH-1', "creditos": 2, "semestre": 2, "prelaciones": [] },
            { "id": 112, "nombre": 'Cálculo III', "codigo": '0253', "creditos": 5, "semestre": 3, "prelaciones": ['0252'] },
            { "id": 113, "nombre": 'Mecánica Aplicada', "codigo": '0602', "creditos": 4, "semestre": 3, "prelaciones": ['0252', '0331'] },
            { "id": 114, "nombre": 'Dibujo de Proyectos', "codigo": '0515', "creditos": 2, "semestre": 3, "prelaciones": ['0552', '0012'] },
            { "id": 115, "nombre": 'Topografía', "codigo": '1265', "creditos": 5, "semestre": 3, "prelaciones": ['0552', '0252'] },
            { "id": 116, "nombre": 'Informática para Ingenieros', "codigo": '1170', "creditos": 2, "semestre": 3, "prelaciones": ['0250'] },
            { "id": 117, "nombre": 'Electiva Socio-Humanística', "codigo": 'ESH-2', "creditos": 2, "semestre": 3, "prelaciones": [] },
            { "id": 118, "nombre": 'Ecuaciones Diferenciales', "codigo": '0256', "creditos": 5, "semestre": 4, "prelaciones": ['0250', '0253'] },
            { "id": 119, "nombre": 'Estática Aplicada', "codigo": '1160', "creditos": 4, "semestre": 4, "prelaciones": ['0602'] },
            { "id": 120, "nombre": 'Estadística para Ingenieros', "codigo": '1765', "creditos": 3, "semestre": 4, "prelaciones": ['0253'] },
            { "id": 121, "nombre": 'Topografía Aplicada a Obras Civiles', "codigo": '1266', "creditos": 2, "semestre": 4, "prelaciones": ['1265', '0515'] },
            { "id": 122, "nombre": 'Química Básica', "codigo": '1460', "creditos": 3, "semestre": 4, "prelaciones": [{"tipo": 'creditos', "valor": 50}] },
            { "id": 123, "nombre": 'Cálculo Vectorial', "codigo": '0254', "creditos": 2, "semestre": 4, "prelaciones": ['0250', '0253'] },
            { "id": 124, "nombre": 'Resistencia de Materiales', "codigo": '1161', "creditos": 5, "semestre": 5, "prelaciones": ['1160', '0254', '0256'] },
            { "id": 125, "nombre": 'Mecánica de Fluidos', "codigo": '1367', "creditos": 4, "semestre": 5, "prelaciones": ['0602', '0254', '0256'] },
            { "id": 126, "nombre": 'Química Aplicada', "codigo": '1468', "creditos": 4, "semestre": 5, "prelaciones": ['1460'] },
            { "id": 127, "nombre": 'Hidrología', "codigo": '1766', "creditos": 4, "semestre": 5, "prelaciones": ['0256', '1765'] },
            { "id": 128, "nombre": 'Geología para Ingenieros', "codigo": '3100', "creditos": 2, "semestre": 5, "prelaciones": ['1266'] },
            { "id": 129, "nombre": 'Electiva Socio-Humanística', "codigo": 'ESH-3', "creditos": 2, "semestre": 5, "prelaciones": [] },
            { "id": 130, "nombre": 'Tecnología del Concreto', "codigo": '1162', "creditos": 4, "semestre": 6, "prelaciones": ['1765', '1161', '1468'] },
            { "id": 131, "nombre": 'Estructuras', "codigo": '1163', "creditos": 6, "semestre": 6, "prelaciones": ['1161'] },
            { "id": 132, "nombre": 'Hombre, Ingeniería y Ambiente', "codigo": '1463', "creditos": 3, "semestre": 6, "prelaciones": [{"tipo": 'creditos', "valor": 90}] },
            { "id": 133, "nombre": 'Mecánica de Suelos I', "codigo": '1560', "creditos": 3, "semestre": 6, "prelaciones": ['3100', '1161', '1367'] },
            { "id": 134, "nombre": 'Laboratorio de Fluidos', "codigo": '1368', "creditos": 1, "semestre": 6, "prelaciones": ['1367'] },
            { "id": 135, "nombre": 'Inglés Instrumental (Civil)', "codigo": '0111', "creditos": 2, "semestre": 6, "prelaciones": [{"tipo": 'creditos', "valor": 80}] },
            { "id": 136, "nombre": 'Concreto Armado', "codigo": '1164', "creditos": 5, "semestre": 7, "prelaciones": ['1163', '1162', '0515'] },
            { "id": 137, "nombre": 'Hidráulica', "codigo": '1366', "creditos": 4, "semestre": 7, "prelaciones": ['1367'] },
            { "id": 138, "nombre": 'Saneamiento Ambiental', "codigo": '1464', "creditos": 4, "semestre": 7, "prelaciones": ['1463'] },
            { "id": 139, "nombre": 'Mecánica de Suelos II', "codigo": '1561', "creditos": 5, "semestre": 7, "prelaciones": ['1560'] },
            { "id": 140, "nombre": 'Proyectos Viales I', "codigo": '1563', "creditos": 4, "semestre": 7, "prelaciones": ['1766', '3100'] },
            { "id": 141, "nombre": 'Proyectos Estructurales de Concreto Armado', "codigo": '1165', "creditos": 5, "semestre": 8, "prelaciones": ['1164', '0111'] },
            { "id": 142, "nombre": 'Sistemas de Abastecimiento', "codigo": '1465', "creditos": 3, "semestre": 8, "prelaciones": ['1366', '1464', '1368'] },
            { "id": 143, "nombre": 'Proyectos Viales II', "codigo": '1564', "creditos": 4, "semestre": 8, "prelaciones": ['1563'] },
            { "id": 144, "nombre": 'Selectiva A-1', "codigo": 'SEL-A1', "creditos": 3, "semestre": 8, "prelaciones": [] },
            { "id": 145, "nombre": 'Selectiva B-1', "codigo": 'SEL-B1', "creditos": 3, "semestre": 8, "prelaciones": [] },
            { "id": 146, "nombre": 'Selectiva C-1', "codigo": 'SEL-C1', "creditos": 3, "semestre": 8, "prelaciones": [] },
            { "id": 147, "nombre": 'Metodología de la Investigación (Civil)', "codigo": '0088', "creditos": 4, "semestre": 9, "prelaciones": [{"tipo": 'creditos', "valor": 140}] },
            { "id": 148, "nombre": 'Cloacas y Drenajes', "codigo": '1466', "creditos": 3, "semestre": 9, "prelaciones": ['1465', '1766'] },
            { "id": 149, "nombre": 'Infraestructura Vial', "codigo": '1562', "creditos": 4, "semestre": 9, "prelaciones": ['1564', '1561'] },
            { "id": 150, "nombre": 'Selectiva A-2', "codigo": 'SEL-A2', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 151, "nombre": 'Selectiva B-2', "codigo": 'SEL-B2', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 152, "nombre": 'Selectiva C-2', "codigo": 'SEL-C2', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 153, "nombre": 'Trabajo de Grado', "codigo": '1010', "creditos": 4, "semestre": 10, "prelaciones": ['0088'] },
            { "id": 154, "nombre": 'Estructuras de Acero', "codigo": '1166', "creditos": 4, "semestre": 10, "prelaciones": ['1163'] },
            { "id": 155, "nombre": 'Instalaciones para Edificios', "codigo": '1467', "creditos": 3, "semestre": 10, "prelaciones": ['1465'] },
            { "id": 156, "nombre": 'Selectiva A-3', "codigo": 'SEL-A3', "creditos": 3, "semestre": 10, "prelaciones": [] },
            { "id": 157, "nombre": 'Selectiva B-3', "codigo": 'SEL-B3', "creditos": 3, "semestre": 10, "prelaciones": [] },
            { "id": 158, "nombre": 'Selectiva C-3', "codigo": 'SEL-C3', "creditos": 3, "semestre": 10, "prelaciones": [] }
        ]
    },
    "quimica": {
        "NOMBRE": "Ingeniería Química", "TOTAL_CREDITOS_CARRERA": 200,
        "pensum": [
            { "id": 201, "nombre": 'Introducción a la Ingeniería', "codigo": '0012', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 202, "nombre": 'Lengua y Comunicación', "codigo": '0183', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 203, "nombre": 'Cálculo I', "codigo": '0251', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 204, "nombre": 'Física General I', "codigo": '0331', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 205, "nombre": 'Geometría Descriptiva I', "codigo": '0551', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 206, "nombre": 'Cálculo II', "codigo": '0252', "creditos": 5, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 207, "nombre": 'Algebra Lineal y Geometría', "codigo": '0250', "creditos": 4, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 208, "nombre": 'Física General II', "codigo": '0332', "creditos": 5, "semestre": 2, "prelaciones": ['0331', '0251'] },
            { "id": 209, "nombre": 'Lab. De Física General', "codigo": '0334', "creditos": 1, "semestre": 2, "prelaciones": ['0331'] },
            { "id": 210, "nombre": 'Química General I', "codigo": '0441', "creditos": 5, "semestre": 2, "prelaciones": [] },
            { "id": 211, "nombre": 'Inglés I', "codigo": '0101', "creditos": 3, "semestre": 3, "prelaciones": [] },
            { "id": 212, "nombre": 'Cálculo III', "codigo": '0253', "creditos": 5, "semestre": 3, "prelaciones": ['0250', '0252'] },
            { "id": 213, "nombre": 'Química Inorgánica', "codigo": '0443', "creditos": 3, "semestre": 3, "prelaciones": ['0441'] },
            { "id": 214, "nombre": 'Programación', "codigo": '0790', "creditos": 4, "semestre": 3, "prelaciones": ['0250'] },
            { "id": 215, "nombre": 'Principios de Ingeniería Química', "codigo": '5300', "creditos": 4, "semestre": 3, "prelaciones": ['0012', '0252', '0441'] },
            { "id": 216, "nombre": 'Industria Química Venezolana', "codigo": '5400', "creditos": 2, "semestre": 3, "prelaciones": ['0183', '0252', '0441'] },
            { "id": 217, "nombre": 'Inglés Instrumental', "codigo": '0105', "creditos": 2, "semestre": 4, "prelaciones": ['0101', {"tipo": 'creditos', "valor": 50}] },
            { "id": 218, "nombre": 'Cálculo Intermedio Aplicado', "codigo": '0264', "creditos": 5, "semestre": 4, "prelaciones": ['0250', '0253'] },
            { "id": 219, "nombre": 'Química Orgánica I', "codigo": '0444', "creditos": 4, "semestre": 4, "prelaciones": ['0443', '5400'] },
            { "id": 220, "nombre": 'Termodinámica (Ing. Químicos)', "codigo": '5310', "creditos": 5, "semestre": 4, "prelaciones": ['0253', '5300'] },
            { "id": 221, "nombre": 'Métodos Numéricos', "codigo": '5411', "creditos": 5, "semestre": 4, "prelaciones": ['0790', '5300'] },
            { "id": 222, "nombre": 'Ec. Dif. en Derivadas Parciales', "codigo": '0257', "creditos": 4, "semestre": 5, "prelaciones": ['0264'] },
            { "id": 223, "nombre": 'Elementos de Estadística', "codigo": '0260', "creditos": 3, "semestre": 5, "prelaciones": ['0253', '0250'] },
            { "id": 224, "nombre": 'Química Orgánica II', "codigo": '0446', "creditos": 4, "semestre": 5, "prelaciones": ['0444'] },
            { "id": 225, "nombre": 'Mecánica de Fluidos', "codigo": '5301', "creditos": 4, "semestre": 5, "prelaciones": ['0264', '0551', '5310'] },
            { "id": 226, "nombre": 'Termodinámica del Equilibrio', "codigo": '5311', "creditos": 5, "semestre": 5, "prelaciones": ['5310', '5411'] },
            { "id": 227, "nombre": 'Electiva no Técnica', "codigo": 'ENT-1', "creditos": 3, "semestre": 6, "prelaciones": [] },
            { "id": 228, "nombre": 'Transferencia de Calor', "codigo": '5302', "creditos": 4, "semestre": 6, "prelaciones": ['0257', '5301'] },
            { "id": 229, "nombre": 'Procesos de Separación', "codigo": '5303', "creditos": 5, "semestre": 6, "prelaciones": ['0105', '5301', '5311'] },
            { "id": 230, "nombre": 'Físico Química', "codigo": '5312', "creditos": 6, "semestre": 6, "prelaciones": ['0446', '5311'] },
            { "id": 231, "nombre": 'Materiales para Ing. Químicos', "codigo": '5430', "creditos": 4, "semestre": 6, "prelaciones": ['0332', '0334', '0444'] },
            { "id": 232, "nombre": 'Economía', "codigo": '0131', "creditos": 3, "semestre": 7, "prelaciones": [{"tipo": 'creditos', "valor": 120}] },
            { "id": 233, "nombre": 'Química Analítica Instrumental', "codigo": '0447', "creditos": 4, "semestre": 7, "prelaciones": ['5312'] },
            { "id": 234, "nombre": 'Transferencia de Masa', "codigo": '5304', "creditos": 4, "semestre": 7, "prelaciones": ['5302', '5303'] },
            { "id": 235, "nombre": 'Lab. de Ingeniería Química I', "codigo": '5305', "creditos": 4, "semestre": 7, "prelaciones": ['0260', '5302'] },
            { "id": 236, "nombre": 'Cinética', "codigo": '5313', "creditos": 4, "semestre": 7, "prelaciones": ['5301', '5312'] },
            { "id": 237, "nombre": 'Procesos Químicos', "codigo": '5465', "creditos": 3, "semestre": 8, "prelaciones": ['5304', '5313'] },
            { "id": 238, "nombre": 'Lab. de Ingeniería Química II', "codigo": '5306', "creditos": 4, "semestre": 8, "prelaciones": ['0447', '5304', '5305'] },
            { "id": 239, "nombre": 'Diseño de Reactores', "codigo": '5314', "creditos": 4, "semestre": 8, "prelaciones": ['5313'] },
            { "id": 240, "nombre": 'Control de Procesos', "codigo": '5412', "creditos": 4, "semestre": 8, "prelaciones": ['5304', '5313'] },
            { "id": 241, "nombre": 'Ingeniería Económica', "codigo": '5420', "creditos": 4, "semestre": 8, "prelaciones": ['0131', '5304'] },
            { "id": 242, "nombre": 'Electiva Técnica', "codigo": 'ET-1', "creditos": 4, "semestre": 9, "prelaciones": [] },
            { "id": 243, "nombre": 'Electiva no Técnica', "codigo": 'ENT-2', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 244, "nombre": 'Diseño', "codigo": '5422', "creditos": 6, "semestre": 9, "prelaciones": ['5412', {"tipo": 'creditos', "valor": 160}] },
            { "id": 245, "nombre": 'Seguridad y Contaminación Industrial', "codigo": '5431', "creditos": 3, "semestre": 9, "prelaciones": ['5306'] },
            { "id": 246, "nombre": 'Trabajo Especial I', "codigo": '5450', "creditos": 4, "semestre": 9, "prelaciones": ['5304', '5314'] },
            { "id": 247, "nombre": 'Electiva Técnica', "codigo": 'ET-2', "creditos": 4, "semestre": 10, "prelaciones": [] },
            { "id": 248, "nombre": 'Electiva Técnica', "codigo": 'ET-3', "creditos": 4, "semestre": 10, "prelaciones": [] },
            { "id": 249, "nombre": 'Trabajo Especial II', "codigo": '5451', "creditos": 8, "semestre": 10, "prelaciones": ['5450'] }
        ]
    },
    "petroleo": {
        "NOMBRE": "Ingeniería de Petróleo", "TOTAL_CREDITOS_CARRERA": 195,
        "pensum": [
            { "id": 301, "nombre": 'Introducción a la Ingeniería', "codigo": '0012', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 302, "nombre": 'Lengua y Comunicación', "codigo": '0183', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 303, "nombre": 'Cálculo I', "codigo": '0251', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 304, "nombre": 'Física General I', "codigo": '0331', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 305, "nombre": 'Geometría Descriptiva I', "codigo": '0551', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 306, "nombre": 'Cálculo II', "codigo": '0252', "creditos": 5, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 307, "nombre": 'Física General II', "codigo": '0332', "creditos": 5, "semestre": 2, "prelaciones": ['0331', '0251'] },
            { "id": 308, "nombre": 'Laboratorio de Física General', "codigo": '0334', "creditos": 1, "semestre": 2, "prelaciones": ['0331'] },
            { "id": 309, "nombre": 'Química General I', "codigo": '0441', "creditos": 5, "semestre": 2, "prelaciones": [] },
            { "id": 310, "nombre": 'Proy. Axonométrica y Acotada', "codigo": '0555', "creditos": 3, "semestre": 2, "prelaciones": ['0551'] },
            { "id": 311, "nombre": 'Algebra Lineal y Geometría', "codigo": '0250', "creditos": 4, "semestre": 3, "prelaciones": ['0251'] },
            { "id": 312, "nombre": 'Cálculo III', "codigo": '0253', "creditos": 5, "semestre": 3, "prelaciones": ['0252'] },
            { "id": 313, "nombre": 'Tópicos de Física General', "codigo": '0333', "creditos": 4, "semestre": 3, "prelaciones": ['0251', '0331'] },
            { "id": 314, "nombre": 'Lab. de Física Instrumental', "codigo": '0335', "creditos": 1, "semestre": 3, "prelaciones": ['0332'] },
            { "id": 315, "nombre": 'Química General II', "codigo": '0442', "creditos": 4, "semestre": 3, "prelaciones": ['0441'] },
            { "id": 316, "nombre": 'Lab. Básico de Química', "codigo": '0445', "creditos": 1, "semestre": 3, "prelaciones": ['0441'] },
            { "id": 317, "nombre": 'Cálculo Vectorial', "codigo": '0254', "creditos": 2, "semestre": 4, "prelaciones": ['0250', '0253'] },
            { "id": 318, "nombre": 'Ecuaciones Diferenciales', "codigo": '0256', "creditos": 5, "semestre": 4, "prelaciones": ['0250', '0253'] },
            { "id": 319, "nombre": 'Química III', "codigo": '0448', "creditos": 2, "semestre": 4, "prelaciones": ['0442'] },
            { "id": 320, "nombre": 'Mecánica', "codigo": '0601', "creditos": 6, "semestre": 4, "prelaciones": ['0250', '0253', '0331'] },
            { "id": 321, "nombre": 'Geología Física', "codigo": '3110', "creditos": 5, "semestre": 4, "prelaciones": [{"tipo": 'creditos', "valor": 50}] },
            { "id": 322, "nombre": 'Introd. a la Ing. de Petróleo', "codigo": '7501', "creditos": 2, "semestre": 4, "prelaciones": ['0012', '0253', '0555', {"tipo": 'creditos', "valor": 50}] },
            { "id": 323, "nombre": 'Inglés I', "codigo": '0101', "creditos": 3, "semestre": 5, "prelaciones": [] },
            { "id": 324, "nombre": 'Elementos de Estadística', "codigo": '0260', "creditos": 3, "semestre": 5, "prelaciones": ['0250', '0253'] },
            { "id": 325, "nombre": 'Resistencia de los Materiales', "codigo": '1100', "creditos": 3, "semestre": 5, "prelaciones": ['0601'] },
            { "id": 326, "nombre": 'Termodinámica', "codigo": '4101', "creditos": 4, "semestre": 5, "prelaciones": ['0254', '0256'] },
            { "id": 327, "nombre": 'Ingeniería de Yacimientos I', "codigo": '7401', "creditos": 3, "semestre": 5, "prelaciones": ['3110', '7501', '0601'] },
            { "id": 328, "nombre": 'Geología Petrolera I', "codigo": '7407', "creditos": 4, "semestre": 5, "prelaciones": ['0555', '3110', '7501'] },
            { "id": 329, "nombre": 'Programación', "codigo": '0790', "creditos": 4, "semestre": 6, "prelaciones": ['0250'] },
            { "id": 330, "nombre": 'Termodinámica II', "codigo": '4102', "creditos": 4, "semestre": 6, "prelaciones": ['4101'] },
            { "id": 331, "nombre": 'Mecánica de Fluidos I', "codigo": '4161', "creditos": 4, "semestre": 6, "prelaciones": ['0254', '0256', '0601'] },
            { "id": 332, "nombre": 'Lab. De Ingeniería de Yacimientos', "codigo": '7403', "creditos": 2, "semestre": 6, "prelaciones": ['7401', '0445', '0335'] },
            { "id": 333, "nombre": 'Geología Petrolera II', "codigo": '7416', "creditos": 3, "semestre": 6, "prelaciones": ['7407'] },
            { "id": 334, "nombre": 'Ingeniería de Yacimientos II', "codigo": '7417', "creditos": 4, "semestre": 6, "prelaciones": ['7401', '0256'] },
            { "id": 335, "nombre": 'Inglés Instrumental', "codigo": '0104', "creditos": 2, "semestre": 7, "prelaciones": ['0101', {"tipo": 'creditos', "valor": 50}] },
            { "id": 336, "nombre": 'Legislación Minera y Petrolera', "codigo": '0142', "creditos": 2, "semestre": 7, "prelaciones": [{"tipo": 'creditos', "valor": 100}] },
            { "id": 337, "nombre": 'Cálculo Numérico', "codigo": '0258', "creditos": 4, "semestre": 7, "prelaciones": ['0256', '0790'] },
            { "id": 338, "nombre": 'Geología Petrolera III', "codigo": '7409', "creditos": 3, "semestre": 7, "prelaciones": ['7416'] },
            { "id": 339, "nombre": 'Ingeniería Petrofísica', "codigo": '7410', "creditos": 3, "semestre": 7, "prelaciones": ['0260', '7407'] },
            { "id": 340, "nombre": 'Ingeniería de Yacimientos III', "codigo": '7418', "creditos": 4, "semestre": 7, "prelaciones": ['4101', '7403', '7417'] },
            { "id": 341, "nombre": 'Pozos I', "codigo": '7502', "creditos": 3, "semestre": 7, "prelaciones": ['1100', '4161'] },
            { "id": 342, "nombre": 'Inglés Conversacional', "codigo": '0106', "creditos": 3, "semestre": 8, "prelaciones": ['0101', {"tipo": 'creditos', "valor": 50}] },
            { "id": 343, "nombre": 'Ingeniería y Sociedad', "codigo": '0184', "creditos": 3, "semestre": 8, "prelaciones": ['0183', {"tipo": 'creditos', "valor": 50}] },
            { "id": 344, "nombre": 'Introd. al Anal. Econ. de Decisiones', "codigo": '0766', "creditos": 3, "semestre": 8, "prelaciones": ['0790', {"tipo": 'creditos', "valor": 120}] },
            { "id": 345, "nombre": 'Ingeniería de Yacimientos IV', "codigo": '7419', "creditos": 4, "semestre": 8, "prelaciones": ['7410', '7418'] },
            { "id": 346, "nombre": 'Lab. de Fluidos de Perforación', "codigo": '7503', "creditos": 2, "semestre": 8, "prelaciones": ['0445', '7502', '7409'] },
            { "id": 347, "nombre": 'Pozos II', "codigo": '7504', "creditos": 3, "semestre": 8, "prelaciones": ['7502'] },
            { "id": 348, "nombre": 'Ingeniería de Producción I', "codigo": '7505', "creditos": 3, "semestre": 8, "prelaciones": ['4102', '7502'] },
            { "id": 349, "nombre": 'Ingeniería de Producción II', "codigo": '7506', "creditos": 3, "semestre": 9, "prelaciones": ['7505'] },
            { "id": 350, "nombre": 'Tecnología de Gas', "codigo": '7507', "creditos": 3, "semestre": 9, "prelaciones": ['7418', '4101'] },
            { "id": 351, "nombre": 'Electiva Técnica', "codigo": 'ETP-1', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 352, "nombre": 'Electiva Técnica', "codigo": 'ETP-2', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 353, "nombre": 'Electiva Técnica', "codigo": 'ETP-3', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 354, "nombre": 'Electiva Técnica', "codigo": 'ETP-4', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 355, "nombre": 'Electiva no Técnica', "codigo": 'ENTP-1', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 356, "nombre": 'Trabajo Especial de Grado', "codigo": '7522', "creditos": 12, "semestre": 10, "prelaciones": [{"tipo": 'creditos', "valor": 170}] }
        ]
    },
    "minas": {
        "NOMBRE": "Ingeniería de Minas", "TOTAL_CREDITOS_CARRERA": 200,
        "pensum": [
            { "id": 401, "nombre": 'Introducción a la Ingeniería', "codigo": '0012', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 402, "nombre": 'Lengua y Comunicación', "codigo": '0183', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 403, "nombre": 'Cálculo I', "codigo": '0251', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 404, "nombre": 'Física General I', "codigo": '0331', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 405, "nombre": 'Geometría Descriptiva I', "codigo": '0551', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 406, "nombre": 'Cálculo II', "codigo": '0252', "creditos": 5, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 407, "nombre": 'Física General II', "codigo": '0332', "creditos": 5, "semestre": 2, "prelaciones": ['0251', '0331'] },
            { "id": 408, "nombre": 'Lab. de Física General', "codigo": '0334', "creditos": 1, "semestre": 2, "prelaciones": ['0331'] },
            { "id": 409, "nombre": 'Química General I', "codigo": '0441', "creditos": 5, "semestre": 2, "prelaciones": [] },
            { "id": 410, "nombre": 'Geología Física', "codigo": '3110', "creditos": 5, "semestre": 2, "prelaciones": [{"tipo": 'creditos', "valor": 19}] },
            { "id": 411, "nombre": 'Cálculo III', "codigo": '0253', "creditos": 5, "semestre": 3, "prelaciones": ['0252'] },
            { "id": 412, "nombre": 'Química General II', "codigo": '0442', "creditos": 4, "semestre": 3, "prelaciones": ['0441'] },
            { "id": 413, "nombre": 'Proy. Axonométrica y Acotada', "codigo": '0555', "creditos": 3, "semestre": 3, "prelaciones": ['0551'] },
            { "id": 414, "nombre": 'Ingeniería Eléctrica', "codigo": '2541', "creditos": 3, "semestre": 3, "prelaciones": ['0332'] },
            { "id": 415, "nombre": 'Introducción a la Minería', "codigo": '3208', "creditos": 4, "semestre": 3, "prelaciones": ['0012'] },
            { "id": 416, "nombre": 'Redacción de Informes Téc.', "codigo": '0185', "creditos": 3, "semestre": 4, "prelaciones": ['0183', {"tipo": 'creditos', "valor": 50}] },
            { "id": 417, "nombre": 'Algebra Lineal y Geometría', "codigo": '0250', "creditos": 4, "semestre": 4, "prelaciones": ['0251'] },
            { "id": 418, "nombre": 'Mecánica Aplicada', "codigo": '0602', "creditos": 4, "semestre": 4, "prelaciones": ['0252', '0331'] },
            { "id": 419, "nombre": 'Fundamentos de Topografía', "codigo": '1205', "creditos": 3, "semestre": 4, "prelaciones": ['0555'] },
            { "id": 420, "nombre": 'Mineralogía y Petrología', "codigo": '3190', "creditos": 4, "semestre": 4, "prelaciones": ['0441', '3110'] },
            { "id": 421, "nombre": 'Docimacia', "codigo": '3210', "creditos": 3, "semestre": 4, "prelaciones": ['0442'] },
            { "id": 422, "nombre": 'Elementos de Estadística', "codigo": '0260', "creditos": 3, "semestre": 5, "prelaciones": ['0250', '0253'] },
            { "id": 423, "nombre": 'Programación', "codigo": '0790', "creditos": 4, "semestre": 5, "prelaciones": ['0250'] },
            { "id": 424, "nombre": 'Mecánica de los Fluidos', "codigo": '1306', "creditos": 4, "semestre": 5, "prelaciones": ['0602'] },
            { "id": 425, "nombre": 'Introd. a la Geol. de Campo', "codigo": '3119', "creditos": 6, "semestre": 5, "prelaciones": ['0555', '3190'] },
            { "id": 426, "nombre": 'Operaciones Mineras', "codigo": '3215', "creditos": 3, "semestre": 5, "prelaciones": ['1205', '3208'] },
            { "id": 427, "nombre": 'Resistencias de Materiales', "codigo": '1100', "creditos": 3, "semestre": 6, "prelaciones": ['0253'] },
            { "id": 428, "nombre": 'Perforación y Voladura de Rocas', "codigo": '3213', "creditos": 3, "semestre": 6, "prelaciones": ['3119'] },
            { "id": 429, "nombre": 'Máquinas y Motores', "codigo": '3222', "creditos": 3, "semestre": 6, "prelaciones": ['0442', '1306'] },
            { "id": 430, "nombre": 'Geología Estructural', "codigo": '3111', "creditos": 4, "semestre": 6, "prelaciones": ['0602', '3119'] },
            { "id": 431, "nombre": 'Yacimientos Minerales Metálicos', "codigo": '3155', "creditos": 4, "semestre": 6, "prelaciones": ['3190'] },
            { "id": 432, "nombre": 'Preparación y Concen. de Minas', "codigo": '3211', "creditos": 4, "semestre": 7, "prelaciones": ['3210', '3155'] },
            { "id": 433, "nombre": 'Infraestructura para Minería', "codigo": '3218', "creditos": 3, "semestre": 7, "prelaciones": ['3222'] },
            { "id": 434, "nombre": 'Cálculos Geomineros', "codigo": '3219', "creditos": 3, "semestre": 7, "prelaciones": ['0250'] },
            { "id": 435, "nombre": 'Mecánica de Rocas', "codigo": '3225', "creditos": 3, "semestre": 7, "prelaciones": ['0602', '3111'] },
            { "id": 436, "nombre": 'Laboreo a Cielo Abierto', "codigo": '3280', "creditos": 4, "semestre": 7, "prelaciones": ['3213', '3215'] },
            { "id": 437, "nombre": 'Geofísica General', "codigo": '3304', "creditos": 3, "semestre": 7, "prelaciones": ['0332', '3119'] },
            { "id": 438, "nombre": 'Minería de Campo', "codigo": '3230', "creditos": 6, "semestre": 8, "prelaciones": ['3211', '3280'] },
            { "id": 439, "nombre": 'Legislación y Economía Minera', "codigo": '3209', "creditos": 3, "semestre": 8, "prelaciones": [{"tipo": 'creditos', "valor": 100}] },
            { "id": 440, "nombre": 'Obras Subterráneas', "codigo": '3223', "creditos": 5, "semestre": 8, "prelaciones": ['3218', '3225'] },
            { "id": 441, "nombre": 'Evaluación de Yacimientos', "codigo": '3235', "creditos": 3, "semestre": 8, "prelaciones": ['3155'] },
            { "id": 442, "nombre": 'Electiva', "codigo": 'EM-1', "creditos": 3, "semestre": 8, "prelaciones": [] },
            { "id": 443, "nombre": 'Electiva', "codigo": 'EM-2', "creditos": 3, "semestre": 8, "prelaciones": [] },
            { "id": 444, "nombre": 'Minería y Ambiente', "codigo": '3224', "creditos": 4, "semestre": 9, "prelaciones": ['3211', '3280'] },
            { "id": 445, "nombre": 'Evaluac. y Geren. de Proy. Mineros', "codigo": '3229', "creditos": 4, "semestre": 9, "prelaciones": ['3209', '3235'] },
            { "id": 446, "nombre": 'Seminario de T.E.G.', "codigo": '3238', "creditos": 2, "semestre": 9, "prelaciones": [{"tipo": 'creditos', "valor": 154}] },
            { "id": 447, "nombre": 'Diseño Geot. de Túneles y Taludes', "codigo": '3292', "creditos": 4, "semestre": 9, "prelaciones": ['3223', '3225'] },
            { "id": 448, "nombre": 'Electiva', "codigo": 'EM-3', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 449, "nombre": 'Electiva', "codigo": 'EM-4', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 450, "nombre": 'Trabajo Especial de Grado', "codigo": '3231', "creditos": 20, "semestre": 10, "prelaciones": ['3238'] }
        ]
    },
    "metalurgica": {
        "NOMBRE": "Ingeniería Metalúrgica", "TOTAL_CREDITOS_CARRERA": 206,
        "pensum": [
            { "id": 501, "nombre": 'Física General I', "codigo": '0331', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 502, "nombre": 'Cálculo I', "codigo": '0251', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 503, "nombre": 'Int. a la Ingeniería', "codigo": '0012', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 504, "nombre": 'Geometría Descriptiva I', "codigo": '0551', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 505, "nombre": 'Lenguaje y Comunicación', "codigo": '0183', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 506, "nombre": 'Física General II', "codigo": '0332', "creditos": 5, "semestre": 2, "prelaciones": ['0331', '0251'] },
            { "id": 507, "nombre": 'Cálculo II', "codigo": '0252', "creditos": 5, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 508, "nombre": 'Dibujo Industrial', "codigo": '0553', "creditos": 2, "semestre": 2, "prelaciones": ['0551'] },
            { "id": 509, "nombre": 'Química I', "codigo": '0441', "creditos": 5, "semestre": 2, "prelaciones": [] },
            { "id": 510, "nombre": 'Algebra Lineal', "codigo": '0250', "creditos": 4, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 511, "nombre": 'Cálculo III', "codigo": '0253', "creditos": 5, "semestre": 3, "prelaciones": ['0252'] },
            { "id": 512, "nombre": 'Química II', "codigo": '0442', "creditos": 4, "semestre": 3, "prelaciones": ['0441', '0251'] },
            { "id": 513, "nombre": 'Lab. Básico de Química', "codigo": '0445', "creditos": 1, "semestre": 3, "prelaciones": ['0441'] },
            { "id": 514, "nombre": 'Programación', "codigo": '0760', "creditos": 4, "semestre": 3, "prelaciones": ['0252', '0250'] },
            { "id": 515, "nombre": 'Lab. de Física Instrumental', "codigo": '0335', "creditos": 1, "semestre": 3, "prelaciones": ['0331'] },
            { "id": 516, "nombre": 'Inglés I', "codigo": '0101', "creditos": 3, "semestre": 3, "prelaciones": [] },
            { "id": 517, "nombre": 'Fisicoquímica', "codigo": '0419', "creditos": 5, "semestre": 4, "prelaciones": ['0253', '0332', '0442'] },
            { "id": 518, "nombre": 'Mecánica', "codigo": '0601', "creditos": 6, "semestre": 4, "prelaciones": ['0331', '0253'] },
            { "id": 519, "nombre": 'Ciencia de los Materiales', "codigo": '6321', "creditos": 4, "semestre": 4, "prelaciones": ['0332', '0442'] },
            { "id": 520, "nombre": 'Cálculo Vectorial', "codigo": '0254', "creditos": 2, "semestre": 4, "prelaciones": ['0253', '0250'] },
            { "id": 521, "nombre": 'Ecuaciones Diferenciales', "codigo": '0256', "creditos": 5, "semestre": 4, "prelaciones": ['0253', '0250'] },
            { "id": 522, "nombre": 'Metalurgia Física I', "codigo": '6311', "creditos": 4, "semestre": 5, "prelaciones": ['6321', '0253'] },
            { "id": 523, "nombre": 'Lab. de Metalurgia Física I', "codigo": '6322', "creditos": 2, "semestre": 5, "prelaciones": ['6321'] },
            { "id": 524, "nombre": 'Termodinámica', "codigo": '6323', "creditos": 4, "semestre": 5, "prelaciones": ['0419'] },
            { "id": 525, "nombre": 'Mecánica de los Fluidos', "codigo": '1306', "creditos": 4, "semestre": 5, "prelaciones": ['0601'] },
            { "id": 526, "nombre": 'Procesos Metalúrgicos', "codigo": '6421', "creditos": 4, "semestre": 5, "prelaciones": ['0419'] },
            { "id": 527, "nombre": 'Cálculo Numérico', "codigo": '0258', "creditos": 4, "semestre": 5, "prelaciones": ['0256', '0760'] },
            { "id": 528, "nombre": 'Metalurgia Física II', "codigo": '6312', "creditos": 4, "semestre": 6, "prelaciones": ['6311', '0254'] },
            { "id": 529, "nombre": 'Lab. de Metalurgia Física II', "codigo": '6315', "creditos": 2, "semestre": 6, "prelaciones": ['6322'] },
            { "id": 530, "nombre": 'Estructura y Prop. de Mat. Cerámicos', "codigo": '6314', "creditos": 4, "semestre": 6, "prelaciones": ['6311'] },
            { "id": 531, "nombre": 'Fenómenos de Transporte', "codigo": '6423', "creditos": 5, "semestre": 6, "prelaciones": ['0258', '1306'] },
            { "id": 532, "nombre": 'Metalurgia Extractiva', "codigo": '6411', "creditos": 4, "semestre": 6, "prelaciones": ['6421'] },
            { "id": 533, "nombre": 'Lab. de Metalurgia Extractiva', "codigo": '6414', "creditos": 2, "semestre": 6, "prelaciones": ['6421'] },
            { "id": 534, "nombre": 'Comportamiento Mecánico', "codigo": '6331', "creditos": 4, "semestre": 7, "prelaciones": ['0601', '6312'] },
            { "id": 535, "nombre": 'Laboratorio Instrumental', "codigo": '6422', "creditos": 4, "semestre": 7, "prelaciones": ['0419', '0445'] },
            { "id": 536, "nombre": 'Hidro y Electrometalurgia', "codigo": '6413', "creditos": 4, "semestre": 7, "prelaciones": ['6411', '6323'] },
            { "id": 537, "nombre": 'Metalurgia de Altas Temperaturas', "codigo": '6412', "creditos": 4, "semestre": 7, "prelaciones": ['6411', '6423', '6323'] },
            { "id": 538, "nombre": 'Metalografía', "codigo": '6335', "creditos": 4, "semestre": 7, "prelaciones": ['6312', '6414'] },
            { "id": 539, "nombre": 'Procesamiento de Metales', "codigo": '6332', "creditos": 4, "semestre": 8, "prelaciones": ['6331', '0553'] },
            { "id": 540, "nombre": 'Siderurgia', "codigo": '6424', "creditos": 5, "semestre": 8, "prelaciones": ['6412'] },
            { "id": 541, "nombre": 'Procesamiento de los Materiales Cerámicos', "codigo": '6446', "creditos": 3, "semestre": 8, "prelaciones": ['6412'] },
            { "id": 542, "nombre": 'Corrosión y Protección', "codigo": '6432', "creditos": 4, "semestre": 8, "prelaciones": ['6413'] },
            { "id": 543, "nombre": 'Lab. de Ensayos Mecánicos', "codigo": '6336', "creditos": 2, "semestre": 8, "prelaciones": ['6331'] },
            { "id": 544, "nombre": 'Ingeniería Económica', "codigo": '6449', "creditos": 3, "semestre": 8, "prelaciones": [{"tipo": 'creditos', "valor": 120}] },
            { "id": 545, "nombre": 'Lab. de Electroquímica y Corrosión', "codigo": '6433', "creditos": 3, "semestre": 9, "prelaciones": ['6432', '6422'] },
            { "id": 546, "nombre": 'Tratamientos Térmicos', "codigo": '6360', "creditos": 4, "semestre": 9, "prelaciones": ['6312', {"tipo": 'creditos', "valor": 140}] },
            { "id": 547, "nombre": 'Electiva Técnica', "codigo": 'ETM-1', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 548, "nombre": 'Electiva Técnica', "codigo": 'ETM-2', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 549, "nombre": 'Electiva no Técnica', "codigo": 'ENTM-1', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 550, "nombre": 'Trabajo Especial I', "codigo": '6033-1', "creditos": 4, "semestre": 9, "prelaciones": [{"tipo": 'creditos', "valor": 160}] },
            { "id": 551, "nombre": 'Fundición', "codigo": '6426', "creditos": 4, "semestre": 10, "prelaciones": ['0553', '6424'] },
            { "id": 552, "nombre": 'Aleaciones no Ferreas', "codigo": '6334', "creditos": 3, "semestre": 10, "prelaciones": ['6332'] },
            { "id": 553, "nombre": 'Electiva Técnica', "codigo": 'ETM-3', "creditos": 3, "semestre": 10, "prelaciones": [] },
            { "id": 554, "nombre": 'Electiva no Técnica', "codigo": 'ENTM-2', "creditos": 3, "semestre": 10, "prelaciones": [] },
            { "id": 555, "nombre": 'Trabajo Especial II', "codigo": '6033-2', "creditos": 4, "semestre": 10, "prelaciones": ['6033-1'] }
        ]
    },
    "geologica": {
        "NOMBRE": "Ingeniería Geológica", "TOTAL_CREDITOS_CARRERA": 200,
        "pensum": [
            { "id": 601, "nombre": 'Introducción a la Ingeniería', "codigo": '0012', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 602, "nombre": 'Lengua y comunicación', "codigo": '0183', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 603, "nombre": 'Cálculo I', "codigo": '0251', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 604, "nombre": 'Física General I', "codigo": '0331', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 605, "nombre": 'Geometría Descriptiva I', "codigo": '0551', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 606, "nombre": 'Cálculo II', "codigo": '0252', "creditos": 5, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 607, "nombre": 'Química General I', "codigo": '0441', "creditos": 5, "semestre": 2, "prelaciones": [] },
            { "id": 608, "nombre": 'Proyección Axonométrica y Acotada', "codigo": '0555', "creditos": 3, "semestre": 2, "prelaciones": ['0551'] },
            { "id": 609, "nombre": 'Geología Física', "codigo": '3110', "creditos": 5, "semestre": 2, "prelaciones": [{"tipo": 'creditos', "valor": 19}] },
            { "id": 610, "nombre": 'Algebra Lineal y geometría', "codigo": '0250', "creditos": 4, "semestre": 3, "prelaciones": ['0251'] },
            { "id": 611, "nombre": 'Cálculo III', "codigo": '0253', "creditos": 5, "semestre": 3, "prelaciones": ['0252'] },
            { "id": 612, "nombre": 'Tópicos de Física General', "codigo": '0333', "creditos": 4, "semestre": 3, "prelaciones": ['0331', '0251'] },
            { "id": 613, "nombre": 'Paleontología', "codigo": '3131', "creditos": 4, "semestre": 3, "prelaciones": ['3110'] },
            { "id": 614, "nombre": 'Interpretación de Mapas', "codigo": '3168', "creditos": 3, "semestre": 3, "prelaciones": ['3110', '0555'] },
            { "id": 615, "nombre": 'Redacción de Informes', "codigo": '0185', "creditos": 3, "semestre": 4, "prelaciones": ['0183', {"tipo": 'creditos', "valor": 50}] },
            { "id": 616, "nombre": 'Elementos de Estadística', "codigo": '0260', "creditos": 3, "semestre": 4, "prelaciones": ['0250', '0253'] },
            { "id": 617, "nombre": 'Mecánica y Elasticidad', "codigo": '0605', "creditos": 5, "semestre": 4, "prelaciones": ['0253', '0331', '0250'] },
            { "id": 618, "nombre": 'Programación', "codigo": '0790', "creditos": 4, "semestre": 4, "prelaciones": ['0250'] },
            { "id": 619, "nombre": 'Mineralogía', "codigo": '3120', "creditos": 5, "semestre": 4, "prelaciones": ['0441', '3110'] },
            { "id": 620, "nombre": 'Inglés I', "codigo": '0101', "creditos": 3, "semestre": 5, "prelaciones": [] },
            { "id": 621, "nombre": 'Geología Estructural', "codigo": '3111', "creditos": 4, "semestre": 5, "prelaciones": ['0605', '3168'] },
            { "id": 622, "nombre": 'Introducción a la Geología de Campo', "codigo": '3119', "creditos": 6, "semestre": 5, "prelaciones": ['3168', '3120'] },
            { "id": 623, "nombre": 'Mineralogía Optica', "codigo": '3121', "creditos": 3, "semestre": 5, "prelaciones": ['3120'] },
            { "id": 624, "nombre": 'Geología Histórica', "codigo": '3130', "creditos": 4, "semestre": 5, "prelaciones": ['3131'] },
            { "id": 625, "nombre": 'Ingeniería y Sociedad', "codigo": '0184', "creditos": 3, "semestre": 6, "prelaciones": ['0183', {"tipo": 'creditos', "valor": 50}] },
            { "id": 626, "nombre": 'Petrología', "codigo": '3122', "creditos": 5, "semestre": 6, "prelaciones": ['3119', '3121'] },
            { "id": 627, "nombre": 'Sedimentología', "codigo": '3129', "creditos": 5, "semestre": 6, "prelaciones": ['3119', '3121'] },
            { "id": 628, "nombre": 'Fotogeología', "codigo": '3143', "creditos": 2, "semestre": 6, "prelaciones": ['3111'] },
            { "id": 629, "nombre": 'Geofísica General', "codigo": '3304', "creditos": 3, "semestre": 6, "prelaciones": ['3119', '0333'] },
            { "id": 630, "nombre": 'Estratigrafía', "codigo": '3136', "creditos": 5, "semestre": 7, "prelaciones": ['3130', '3129'] },
            { "id": 631, "nombre": 'Geotecnia I', "codigo": '3150', "creditos": 4, "semestre": 7, "prelaciones": ['3111', '0253'] },
            { "id": 632, "nombre": 'Geomorfología', "codigo": '3181', "creditos": 4, "semestre": 7, "prelaciones": ['3119', '3111'] },
            { "id": 633, "nombre": 'Geología de Campo', "codigo": '3141', "creditos": 6, "semestre": 8, "prelaciones": ['3129', '3143'] },
            { "id": 634, "nombre": 'Geología de Venezuela', "codigo": '3134', "creditos": 4, "semestre": 8, "prelaciones": ['3136'] },
            { "id": 635, "nombre": 'Laboratorio de Geología de Campo', "codigo": '3142', "creditos": 3, "semestre": 8, "prelaciones": ['3141'] },
            { "id": 636, "nombre": 'Yacimientos Minerales Metálicos', "codigo": '3155', "creditos": 4, "semestre": 8, "prelaciones": ['3122'] },
            { "id": 637, "nombre": 'Seminario', "codigo": '3144', "creditos": 3, "semestre": 9, "prelaciones": [{"tipo": 'creditos', "valor": 140}] },
            { "id": 638, "nombre": 'Proyecto de Trabajo Especial de Grado', "codigo": '3146', "creditos": 2, "semestre": 9, "prelaciones": ['3141'] },
            { "id": 639, "nombre": 'Geología del Petróleo', "codigo": '3157', "creditos": 3, "semestre": 9, "prelaciones": [{"tipo": 'creditos', "valor": 140}] },
            { "id": 640, "nombre": 'Economía y Legislación Minera', "codigo": '3209', "creditos": 3, "semestre": 9, "prelaciones": [{"tipo": 'creditos', "valor": 100}] },
            { "id": 641, "nombre": 'Trabajo Especial de Grado', "codigo": '3145', "creditos": 20, "semestre": 10, "prelaciones": ['3146'] }
        ]
    },
    "geofisica": {
        "NOMBRE": "Ingeniería Geofísica", "TOTAL_CREDITOS_CARRERA": 200,
        "pensum": [
            { "id": 701, "nombre": 'Introducción a la Ingeniería', "codigo": '0012', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 702, "nombre": 'Lengua y Comunicación', "codigo": '0183', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 703, "nombre": 'Cálculo I', "codigo": '0251', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 704, "nombre": 'Física General I', "codigo": '0331', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 705, "nombre": 'Geometría Descriptiva I', "codigo": '0551', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 706, "nombre": 'Cálculo II', "codigo": '0252', "creditos": 5, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 707, "nombre": 'Tópicos de Física General', "codigo": '0333', "creditos": 4, "semestre": 2, "prelaciones": ['0251', '0331'] },
            { "id": 708, "nombre": 'Proy. Axonométrica y Acotada', "codigo": '0555', "creditos": 3, "semestre": 2, "prelaciones": ['0551'] },
            { "id": 709, "nombre": 'Geología Física', "codigo": '3110', "creditos": 5, "semestre": 2, "prelaciones": [{"tipo": 'creditos', "valor": 19}] },
            { "id": 710, "nombre": 'Introducción a la Geofísica', "codigo": '3384', "creditos": 3, "semestre": 2, "prelaciones": ['0012', '0331'] },
            { "id": 711, "nombre": 'Inglés I', "codigo": '0101', "creditos": 3, "semestre": 3, "prelaciones": [{"tipo": 'creditos', "valor": 35}] },
            { "id": 712, "nombre": 'Algebra Lineal y Geometría', "codigo": '0250', "creditos": 4, "semestre": 3, "prelaciones": ['0251'] },
            { "id": 713, "nombre": 'Cálculo III', "codigo": '0253', "creditos": 5, "semestre": 3, "prelaciones": ['0252'] },
            { "id": 714, "nombre": 'Física General II', "codigo": '0332', "creditos": 4, "semestre": 3, "prelaciones": ['0331'] },
            { "id": 715, "nombre": 'Química General I', "codigo": '0441', "creditos": 5, "semestre": 3, "prelaciones": [] },
            { "id": 716, "nombre": 'Redacción de Informes Tec.', "codigo": '0185', "creditos": 3, "semestre": 4, "prelaciones": ['0183', {"tipo": 'creditos', "valor": 50}] },
            { "id": 717, "nombre": 'Ecuaciones Diferenciales', "codigo": '0256', "creditos": 5, "semestre": 4, "prelaciones": ['0250', '0252'] },
            { "id": 718, "nombre": 'Mecánica y Elasticidad', "codigo": '0605', "creditos": 5, "semestre": 4, "prelaciones": ['0253', '0331', '0250'] },
            { "id": 719, "nombre": 'Programación', "codigo": '0790', "creditos": 4, "semestre": 4, "prelaciones": ['0250'] },
            { "id": 720, "nombre": 'Mineralogía y Petrología', "codigo": '3190', "creditos": 4, "semestre": 4, "prelaciones": ['0441', '3110'] },
            { "id": 721, "nombre": 'Electiva', "codigo": 'EGF-1', "creditos": 3, "semestre": 5, "prelaciones": [] },
            { "id": 722, "nombre": 'Elementos de Estadística', "codigo": '0260', "creditos": 3, "semestre": 5, "prelaciones": ['0253', '0250'] },
            { "id": 723, "nombre": 'Introd. a la Geol. de Campo', "codigo": '3119', "creditos": 6, "semestre": 5, "prelaciones": ['0555', '3190'] },
            { "id": 724, "nombre": 'Met. Matemática de la Física', "codigo": '3301', "creditos": 3, "semestre": 5, "prelaciones": ['0256', '0333'] },
            { "id": 725, "nombre": 'Instrumentación', "codigo": '3383', "creditos": 5, "semestre": 5, "prelaciones": ['0332', '3384'] },
            { "id": 726, "nombre": 'Teoría de Filtro', "codigo": '3330', "creditos": 4, "semestre": 5, "prelaciones": ['0256'] },
            { "id": 727, "nombre": 'Electiva', "codigo": 'EGF-2', "creditos": 3, "semestre": 6, "prelaciones": [] },
            { "id": 728, "nombre": 'Ingeniería y Sociedad', "codigo": '0184', "creditos": 3, "semestre": 6, "prelaciones": ['0183', {"tipo": 'creditos', "valor": 50}] },
            { "id": 729, "nombre": 'Geología Estructural', "codigo": '3111', "creditos": 4, "semestre": 6, "prelaciones": ['0605', '3119'] },
            { "id": 730, "nombre": 'Métodos Eléctricos', "codigo": '3306', "creditos": 4, "semestre": 6, "prelaciones": ['3383'] },
            { "id": 731, "nombre": 'Inglés Instrumental', "codigo": '0104', "creditos": 2, "semestre": 6, "prelaciones": ['0101', {"tipo": 'creditos', "valor": 57}] },
            { "id": 732, "nombre": 'Métodos Sísmicos', "codigo": '3309', "creditos": 5, "semestre": 6, "prelaciones": ['3330', '3301'] },
            { "id": 733, "nombre": 'Electiva', "codigo": 'EGF-3', "creditos": 3, "semestre": 7, "prelaciones": [] },
            { "id": 734, "nombre": 'Electiva', "codigo": 'EGF-4', "creditos": 3, "semestre": 7, "prelaciones": [] },
            { "id": 735, "nombre": 'Estrat. y Sedimentación', "codigo": '3164', "creditos": 3, "semestre": 7, "prelaciones": ['3111'] },
            { "id": 736, "nombre": 'Met. Grav. y Magnético', "codigo": '3307', "creditos": 5, "semestre": 7, "prelaciones": ['3383', '3111'] },
            { "id": 737, "nombre": 'Economía y Legislación Minera', "codigo": '3209', "creditos": 3, "semestre": 7, "prelaciones": [{"tipo": 'creditos', "valor": 100}] },
            { "id": 738, "nombre": 'Geofísica de Campo', "codigo": '3311', "creditos": 4, "semestre": 8, "prelaciones": ['3306', '3307', '3309'] },
            { "id": 739, "nombre": 'Electiva', "codigo": 'EGF-5', "creditos": 3, "semestre": 8, "prelaciones": [] },
            { "id": 740, "nombre": 'Electiva', "codigo": 'EGF-6', "creditos": 3, "semestre": 8, "prelaciones": [] },
            { "id": 741, "nombre": 'Ppios. Geología de Vzla.', "codigo": '3135', "creditos": 3, "semestre": 8, "prelaciones": ['3164'] },
            { "id": 742, "nombre": 'Geomatemática I', "codigo": '3327', "creditos": 4, "semestre": 8, "prelaciones": ['0260', '3301'] },
            { "id": 743, "nombre": 'Lab. Geof. de Campo', "codigo": '3329', "creditos": 4, "semestre": 8, "prelaciones": ['3311', '0185'] },
            { "id": 744, "nombre": 'Electiva', "codigo": 'EGF-7', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 745, "nombre": 'Electiva', "codigo": 'EGF-8', "creditos": 3, "semestre": 9, "prelaciones": [] },
            { "id": 746, "nombre": 'Sismología', "codigo": '3310', "creditos": 4, "semestre": 9, "prelaciones": ['3111', '3330', '3301'] },
            { "id": 747, "nombre": 'Seminario T.E.G.', "codigo": '3313', "creditos": 2, "semestre": 9, "prelaciones": ['3311'] },
            { "id": 748, "nombre": 'Petrofísica Aplicada', "codigo": '3191', "creditos": 3, "semestre": 9, "prelaciones": ['3306', '3309'] },
            { "id": 749, "nombre": 'Metodología de la Investigación', "codigo": '0188', "creditos": 3, "semestre": 9, "prelaciones": [{"tipo": 'creditos', "valor": 150}] },
            { "id": 750, "nombre": 'Trabajo Especial de Grado', "codigo": '3315', "creditos": 20, "semestre": 10, "prelaciones": ['3313', '3329'] }
        ]
    },
    "geodesica": {
        "NOMBRE": "Ingeniería Geodésica", "TOTAL_CREDITOS_CARRERA": 200,
        "pensum": [
            { "id": 801, "nombre": 'Física General I', "codigo": '0331', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 802, "nombre": 'Geometría Descriptiva I', "codigo": '0551', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 803, "nombre": 'Cálculo I', "codigo": '0251', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 804, "nombre": 'Introducción a la Ingeniería', "codigo": '0012', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 805, "nombre": 'Lengua y Comunicación', "codigo": '0183', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 806, "nombre": 'Laboratorio Física General I', "codigo": '0334', "creditos": 1, "semestre": 2, "prelaciones": ['0331'] },
            { "id": 807, "nombre": 'Tópicos Física General', "codigo": '0333', "creditos": 4, "semestre": 2, "prelaciones": ['0251', '0331'] },
            { "id": 808, "nombre": 'Geometría Descriptiva II', "codigo": '0552', "creditos": 4, "semestre": 2, "prelaciones": ['0551'] },
            { "id": 809, "nombre": 'Cálculo II', "codigo": '0252', "creditos": 5, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 810, "nombre": 'Álgebra Lineal y Geometría', "codigo": '0250', "creditos": 4, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 811, "nombre": 'Inglés I', "codigo": '0101', "creditos": 3, "semestre": 2, "prelaciones": [] },
            { "id": 812, "nombre": 'Lab. Física Inst. para Geodesta', "codigo": '0336', "creditos": 1, "semestre": 3, "prelaciones": ['0333'] },
            { "id": 813, "nombre": 'Mecánica Aplicada', "codigo": '0602', "creditos": 4, "semestre": 3, "prelaciones": ['0252', '0331'] },
            { "id": 814, "nombre": 'Topografía', "codigo": '1207', "creditos": 5, "semestre": 3, "prelaciones": ['0552', '0333'] },
            { "id": 815, "nombre": 'Cálculo III', "codigo": '0253', "creditos": 5, "semestre": 3, "prelaciones": ['0252'] },
            { "id": 816, "nombre": 'Química Básica', "codigo": '1460', "creditos": 3, "semestre": 3, "prelaciones": [{"tipo": 'creditos', "valor": 40}] },
            { "id": 817, "nombre": 'Dibujo Topográfico', "codigo": '1200', "creditos": 2, "semestre": 4, "prelaciones": ['1207'] },
            { "id": 818, "nombre": 'Topografía Geodésica', "codigo": '1208', "creditos": 5, "semestre": 4, "prelaciones": ['1207'] },
            { "id": 819, "nombre": 'Ecuaciones Diferenciales', "codigo": '0256', "creditos": 5, "semestre": 4, "prelaciones": ['0253', '0250'] },
            { "id": 820, "nombre": 'Elementos de Estadística', "codigo": '0260', "creditos": 3, "semestre": 4, "prelaciones": ['0250', '0253'] },
            { "id": 821, "nombre": 'Cálculo Vectorial', "codigo": '0254', "creditos": 2, "semestre": 4, "prelaciones": ['0253', '0250'] },
            { "id": 822, "nombre": 'Fotogrametría', "codigo": '1231', "creditos": 4, "semestre": 5, "prelaciones": ['1208', '1200'] },
            { "id": 823, "nombre": 'Hidrología', "codigo": '1701', "creditos": 4, "semestre": 5, "prelaciones": ['0254', '0256'] },
            { "id": 824, "nombre": 'Agrimensura Legal', "codigo": '1251', "creditos": 2, "semestre": 5, "prelaciones": ['1208'] },
            { "id": 825, "nombre": 'Método Matemático Geodésico', "codigo": '1209', "creditos": 5, "semestre": 5, "prelaciones": ['0260', '1208'] },
            { "id": 826, "nombre": 'Deontología para Ing. Geodesta', "codigo": '0146', "creditos": 2, "semestre": 5, "prelaciones": ['1208', {"tipo": 'creditos', "valor": 80}] },
            { "id": 827, "nombre": 'Programación', "codigo": '0790', "creditos": 4, "semestre": 5, "prelaciones": ['0250'] },
            { "id": 828, "nombre": 'Fotogrametría II', "codigo": '1232', "creditos": 4, "semestre": 6, "prelaciones": ['1231'] },
            { "id": 829, "nombre": 'Geología Aplicada', "codigo": '3107', "creditos": 4, "semestre": 6, "prelaciones": ['0602', '1701'] },
            { "id": 830, "nombre": 'Catastro y Valuación', "codigo": '1252', "creditos": 4, "semestre": 6, "prelaciones": ['1251'] },
            { "id": 831, "nombre": 'Errores de Medición', "codigo": '1241', "creditos": 4, "semestre": 6, "prelaciones": ['1209', '0790'] },
            { "id": 832, "nombre": 'Astronomía Geodésica', "codigo": '1223', "creditos": 4, "semestre": 6, "prelaciones": ['1208'] },
            { "id": 833, "nombre": 'Higiene y Primeros Auxilios', "codigo": '1261', "creditos": 2, "semestre": 6, "prelaciones": [{"tipo": 'creditos', "valor": 57}] },
            { "id": 834, "nombre": 'Fotogrametría III', "codigo": '1233', "creditos": 4, "semestre": 7, "prelaciones": ['1232'] },
            { "id": 835, "nombre": 'Fotointerpretación', "codigo": '1235', "creditos": 3, "semestre": 7, "prelaciones": ['1231', '3107'] },
            { "id": 836, "nombre": 'Ingeniería de Valuación', "codigo": '1236', "creditos": 4, "semestre": 7, "prelaciones": ['1252', '0260'] },
            { "id": 837, "nombre": 'Geodesia I', "codigo": '1211', "creditos": 4, "semestre": 7, "prelaciones": ['1223'] },
            { "id": 838, "nombre": 'Electiva', "codigo": 'EGD-1', "creditos": 3, "semestre": 7, "prelaciones": [] },
            { "id": 839, "nombre": 'Electiva sociohumanística', "codigo": 'ESHGD-1', "creditos": 2, "semestre": 7, "prelaciones": [] },
            { "id": 840, "nombre": 'Sensores Remotos', "codigo": '1257', "creditos": 3, "semestre": 8, "prelaciones": ['1233', '1235'] },
            { "id": 841, "nombre": 'Geofísica General', "codigo": '3304', "creditos": 3, "semestre": 8, "prelaciones": ['3107'] },
            { "id": 842, "nombre": 'Proyectos Viales I', "codigo": '1563', "creditos": 4, "semestre": 8, "prelaciones": ['1207'] },
            { "id": 843, "nombre": 'Geodesia II', "codigo": '1212', "creditos": 4, "semestre": 8, "prelaciones": ['1211'] },
            { "id": 844, "nombre": 'Cartografía', "codigo": '1215', "creditos": 5, "semestre": 8, "prelaciones": ['1211'] },
            { "id": 845, "nombre": 'Electiva', "codigo": 'EGD-2', "creditos": 3, "semestre": 8, "prelaciones": [] },
            { "id": 846, "nombre": 'Trabajo Especial de Grado I', "codigo": '1259-1', "creditos": 3, "semestre": 9, "prelaciones": [{"tipo": 'creditos', "valor": 140}] },
            { "id": 847, "nombre": 'Mediciones de Ingeniería', "codigo": '1238', "creditos": 5, "semestre": 9, "prelaciones": ['1212'] },
            { "id": 848, "nombre": 'Compensación de errores', "codigo": '1242', "creditos": 4, "semestre": 9, "prelaciones": ['1241'] },
            { "id": 849, "nombre": 'Geodesia III', "codigo": '1213', "creditos": 5, "semestre": 9, "prelaciones": ['1212'] },
            { "id": 850, "nombre": 'Cartografía Automatizada', "codigo": '1239', "creditos": 4, "semestre": 9, "prelaciones": ['1215', '0790'] },
            { "id": 851, "nombre": 'Trabajo Especial de Grado II', "codigo": '1259-2', "creditos": 5, "semestre": 10, "prelaciones": ['1259-1'] },
            { "id": 852, "nombre": 'Administración Proyecto Geodésico', "codigo": '1253', "creditos": 4, "semestre": 10, "prelaciones": ['1212', '1242'] },
            { "id": 853, "nombre": 'Geodesia IV', "codigo": '1254', "creditos": 5, "semestre": 10, "prelaciones": ['1213'] },
            { "id": 854, "nombre": 'Electiva', "codigo": 'EGD-3', "creditos": 4, "semestre": 10, "prelaciones": [] },
            { "id": 855, "nombre": 'Electiva sociohumanística', "codigo": 'ESHGD-2', "creditos": 2, "semestre": 10, "prelaciones": [] }
        ]
    },
    "electrica_potencia": {
        "NOMBRE": "Ingeniería Eléctrica - Potencia", "TOTAL_CREDITOS_CARRERA": 204,
        "pensum": [
            { "id": 901, "nombre": 'Física General I', "codigo": '0331', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 902, "nombre": 'Cálculo I', "codigo": '0251', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 903, "nombre": 'Introducción a la Ingeniería', "codigo": '0012', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 904, "nombre": 'Lengua y Comunicación', "codigo": '0183', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 905, "nombre": 'Geometría Descriptiva I', "codigo": '0551', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 906, "nombre": 'Álgebra Lineal y Geometría', "codigo": '0250', "creditos": 4, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 907, "nombre": 'Cálculo II', "codigo": '0252', "creditos": 5, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 908, "nombre": 'Física General II', "codigo": '0332', "creditos": 5, "semestre": 2, "prelaciones": ['0251', '0331'] },
            { "id": 909, "nombre": 'Química General I', "codigo": '0441', "creditos": 5, "semestre": 2, "prelaciones": [] },
            { "id": 910, "nombre": 'Laboratorio de Física I', "codigo": '0334', "creditos": 1, "semestre": 2, "prelaciones": ['0331'] },
            { "id": 911, "nombre": 'Cálculo III', "codigo": '0253', "creditos": 5, "semestre": 3, "prelaciones": ['0252'] },
            { "id": 912, "nombre": 'Ecuaciones Diferenciales Ordinarias', "codigo": '0255', "creditos": 5, "semestre": 3, "prelaciones": ['0250', '0252'] },
            { "id": 913, "nombre": 'Programación', "codigo": '0790', "creditos": 4, "semestre": 3, "prelaciones": ['0250'] },
            { "id": 914, "nombre": 'Mecánica Aplicada', "codigo": '0602', "creditos": 4, "semestre": 3, "prelaciones": ['0331', '0252'] },
            { "id": 915, "nombre": 'Electiva Humanística', "codigo": 'EH-1', "creditos": 2, "semestre": 3, "prelaciones": [] },
            { "id": 916, "nombre": 'Tópicos de Física General', "codigo": '0333', "creditos": 4, "semestre": 4, "prelaciones": ['0251', '0331', '0253'] },
            { "id": 917, "nombre": 'Redes Eléctricas I', "codigo": '2107', "creditos": 5, "semestre": 4, "prelaciones": ['0255', '0332'] },
            { "id": 918, "nombre": 'Variable Compleja y Cálculo Operacional', "codigo": '2515', "creditos": 4, "semestre": 4, "prelaciones": ['0253', '0255'] },
            { "id": 919, "nombre": 'Cálculo Vectorial', "codigo": '0254', "creditos": 2, "semestre": 4, "prelaciones": ['0250', '0253'] },
            { "id": 920, "nombre": 'Redacción de Informes', "codigo": '0185', "creditos": 3, "semestre": 4, "prelaciones": ['0183', {"tipo": 'creditos', "valor": 50}] },
            { "id": 921, "nombre": 'Electiva Humanística', "codigo": 'EH-2', "creditos": 2, "semestre": 4, "prelaciones": [] },
            { "id": 922, "nombre": 'Cálculo Numérico', "codigo": '2514', "creditos": 4, "semestre": 5, "prelaciones": ['0255', '0790'] },
            { "id": 923, "nombre": 'Redes Eléctricas II', "codigo": '2108', "creditos": 4, "semestre": 5, "prelaciones": ['0790', '2107', '2515'] },
            { "id": 924, "nombre": 'Lab. Ingeniería Eléctrica I', "codigo": '2112', "creditos": 1, "semestre": 5, "prelaciones": ['2107'] },
            { "id": 925, "nombre": 'Electrónica I', "codigo": '2216', "creditos": 5, "semestre": 5, "prelaciones": ['2107'] },
            { "id": 926, "nombre": 'Análisis de Sistemas Lineales', "codigo": '2507', "creditos": 4, "semestre": 5, "prelaciones": ['0790', '2107', '2515'] },
            { "id": 927, "nombre": 'Probabilidades', "codigo": '2508', "creditos": 3, "semestre": 5, "prelaciones": ['2515'] },
            { "id": 928, "nombre": 'Lógica Digital', "codigo": '2233', "creditos": 3, "semestre": 6, "prelaciones": ['2107'] },
            { "id": 929, "nombre": 'Teoría Electromagnética', "codigo": '2124', "creditos": 4, "semestre": 6, "prelaciones": ['0333', '2107'] },
            { "id": 930, "nombre": 'Redes Eléctricas III', "codigo": '2109', "creditos": 4, "semestre": 6, "prelaciones": ['2108', '2507'] },
            { "id": 931, "nombre": 'Lab. Ingeniería Eléctrica II', "codigo": '2113', "creditos": 1, "semestre": 6, "prelaciones": ['2108', '2112'] },
            { "id": 932, "nombre": 'Electrónica II', "codigo": '2217', "creditos": 5, "semestre": 6, "prelaciones": ['2112', '2216', '2507'] },
            { "id": 933, "nombre": 'Sistemas de Telecomunicaciones I', "codigo": '2415', "creditos": 3, "semestre": 6, "prelaciones": ['2507', '2508'] },
            { "id": 934, "nombre": 'Sistemas de Control I', "codigo": '2222', "creditos": 5, "semestre": 7, "prelaciones": ['2217', '2507'] },
            { "id": 935, "nombre": 'Sistemas de Potencia I', "codigo": '2345', "creditos": 3, "semestre": 7, "prelaciones": ['2109'] },
            { "id": 936, "nombre": 'Comunicaciones I', "codigo": '2426', "creditos": 5, "semestre": 7, "prelaciones": ['2109', '2415'] },
            { "id": 937, "nombre": 'Conversión de Energía', "codigo": '2132', "creditos": 3, "semestre": 7, "prelaciones": ['0441', '0602', '2124'] },
            { "id": 938, "nombre": 'Sistemas Digitales I', "codigo": '2234', "creditos": 3, "semestre": 7, "prelaciones": ['2217', '2233'] },
            { "id": 939, "nombre": 'Ejercicio Profesional y Gerencia', "codigo": '2520', "creditos": 4, "semestre": 8, "prelaciones": [{"tipo": 'creditos', "valor": 130}] },
            { "id": 940, "nombre": 'Máquinas Eléctricas I', "codigo": '2315', "creditos": 6, "semestre": 8, "prelaciones": ['2109', '2112', '2124'] },
            { "id": 941, "nombre": 'Sistemas de Potencia II', "codigo": '2346', "creditos": 4, "semestre": 8, "prelaciones": ['2345'] },
            { "id": 942, "nombre": 'Plantas y Subestaciones', "codigo": '2349', "creditos": 4, "semestre": 8, "prelaciones": ['2345'] },
            { "id": 943, "nombre": 'Sistemas de Transmisión y Distribución', "codigo": '2351', "creditos": 4, "semestre": 8, "prelaciones": ['2345'] },
            { "id": 944, "nombre": 'Sobretensiones Transitorias', "codigo": '2360', "creditos": 4, "semestre": 9, "prelaciones": ['2346'] },
            { "id": 945, "nombre": 'Máquinas Eléctricas II', "codigo": '2316', "creditos": 5, "semestre": 9, "prelaciones": ['2315'] },
            { "id": 946, "nombre": 'Lab. de Máquinas Eléctricas', "codigo": '2317', "creditos": 3, "semestre": 9, "prelaciones": ['2315'] },
            { "id": 947, "nombre": 'Trabajo de Grado I', "codigo": '2383', "creditos": 4, "semestre": 9, "prelaciones": [{"tipo": 'creditos', "valor": 150}] },
            { "id": 948, "nombre": 'Sistema de Protección I', "codigo": '2348', "creditos": 4, "semestre": 9, "prelaciones": ['2346'] },
            { "id": 949, "nombre": 'Electiva', "codigo": 'EEP-1', "creditos": 4, "semestre": 10, "prelaciones": [{"tipo": 'creditos', "valor": 150}] },
            { "id": 950, "nombre": 'Sistema de Potencia III', "codigo": '2347', "creditos": 4, "semestre": 10, "prelaciones": ['2316', '2346'] },
            { "id": 951, "nombre": 'Trabajo de Grado II', "codigo": '2284', "creditos": 9, "semestre": 10, "prelaciones": ['2383'] },
            { "id": 952, "nombre": 'Ingeniería Económica', "codigo": '2523', "creditos": 4, "semestre": 10, "prelaciones": ['2520'] }
        ]
    },
    "electrica_comunicaciones": {
        "NOMBRE": "Ingeniería Eléctrica - Comunicaciones", "TOTAL_CREDITOS_CARRERA": 199,
        "pensum": [
            { "id": 1001, "nombre": 'Física General I', "codigo": '0331', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 1002, "nombre": 'Cálculo I', "codigo": '0251', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 1003, "nombre": 'Introducción a la Ingeniería', "codigo": '0012', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 1004, "nombre": 'Lengua y Comunicación', "codigo": '0183', "creditos": 2, "semestre": 1, "prelaciones": [] },
            { "id": 1005, "nombre": 'Geometría Descriptiva I', "codigo": '0551', "creditos": 5, "semestre": 1, "prelaciones": [] },
            { "id": 1006, "nombre": 'Álgebra Lineal y Geometría', "codigo": '0250', "creditos": 4, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 1007, "nombre": 'Cálculo II', "codigo": '0252', "creditos": 5, "semestre": 2, "prelaciones": ['0251'] },
            { "id": 1008, "nombre": 'Física General II', "codigo": '0332', "creditos": 5, "semestre": 2, "prelaciones": ['0251', '0331'] },
            { "id": 1009, "nombre": 'Química General I', "codigo": '0441', "creditos": 5, "semestre": 2, "prelaciones": [] },
            { "id": 1010, "nombre": 'Laboratorio de Física I', "codigo": '0334', "creditos": 1, "semestre": 2, "prelaciones": ['0331'] },
            { "id": 1011, "nombre": 'Cálculo III', "codigo": '0253', "creditos": 5, "semestre": 3, "prelaciones": ['0252'] },
            { "id": 1012, "nombre": 'Ecuaciones Diferenciales Ordinarias', "codigo": '0255', "creditos": 5, "semestre": 3, "prelaciones": ['0250', '0252'] },
            { "id": 1013, "nombre": 'Programación', "codigo": '0790', "creditos": 4, "semestre": 3, "prelaciones": ['0250'] },
            { "id": 1014, "nombre": 'Mecánica Aplicada', "codigo": '0602', "creditos": 4, "semestre": 3, "prelaciones": ['0331', '0252'] },
            { "id": 1015, "nombre": 'Electiva Humanística', "codigo": 'EH-1', "creditos": 2, "semestre": 3, "prelaciones": [] },
            { "id": 1016, "nombre": 'Tópicos de Física General', "codigo": '0333', "creditos": 4, "semestre": 4, "prelaciones": ['0251', '0331', '0253'] },
            { "id": 1017, "nombre": 'Redes Eléctricas I', "codigo": '2107', "creditos": 5, "semestre": 4, "prelaciones": ['0255', '0332'] },
            { "id": 1018, "nombre": 'Variable Compleja y Cálculo Operacional', "codigo": '2515', "creditos": 4, "semestre": 4, "prelaciones": ['0253', '0255'] },
            { "id": 1019, "nombre": 'Cálculo Vectorial', "codigo": '0254', "creditos": 2, "semestre": 4, "prelaciones": ['0250', '0253'] },
            { "id": 1020, "nombre": 'Redacción de Informes', "codigo": '0185', "creditos": 3, "semestre": 4, "prelaciones": ['0183', {"tipo": 'creditos', "valor": 50}] },
            { "id": 1021, "nombre": 'Electiva Humanística', "codigo": 'EH-2', "creditos": 2, "semestre": 4, "prelaciones": [] },
            { "id": 1022, "nombre": 'Cálculo Numérico', "codigo": '2514', "creditos": 4, "semestre": 5, "prelaciones": ['0255', '0790'] },
            { "id": 1023, "nombre": 'Redes Eléctricas II', "codigo": '2108', "creditos": 4, "semestre": 5, "prelaciones": ['0790', '2107', '2515'] },
            { "id": 1024, "nombre": 'Lab. Ingeniería Eléctrica I', "codigo": '2112', "creditos": 1, "semestre": 5, "prelaciones": ['2107'] },
            { "id": 1025, "nombre": 'Electrónica I', "codigo": '2216', "creditos": 5, "semestre": 5, "prelaciones": ['2107'] },
            { "id": 1026, "nombre": 'Análisis de Sistemas Lineales', "codigo": '2507', "creditos": 4, "semestre": 5, "prelaciones": ['0790', '2107', '2515'] },
            { "id": 1027, "nombre": 'Probabilidades', "codigo": '2508', "creditos": 3, "semestre": 5, "prelaciones": ['2515'] },
            { "id": 1028, "nombre": 'Lógica Digital', "codigo": '2233', "creditos": 3, "semestre": 6, "prelaciones": ['2107'] },
            { "id": 1029, "nombre": 'Teoría Electromagnética', "codigo": '2124', "creditos": 4, "semestre": 6, "prelaciones": ['0333', '2107'] },
            { "id": 1030, "nombre": 'Redes Eléctricas III', "codigo": '2109', "creditos": 4, "semestre": 6, "prelaciones": ['2108', '2507'] },
            { "id": 1031, "nombre": 'Lab. Ingeniería Eléctrica II', "codigo": '2113', "creditos": 1, "semestre": 6, "prelaciones": ['2108', '2112'] },
            { "id": 1032, "nombre": 'Electrónica II', "codigo": '2217', "creditos": 5, "semestre": 6, "prelaciones": ['2112', '2216', '2507'] },
            { "id": 1033, "nombre": 'Sistemas de Telecomunicaciones I', "codigo": '2415', "creditos": 3, "semestre": 6, "prelaciones": ['2507', '2508'] },
            { "id": 1034, "nombre": 'Sistemas de Control I', "codigo": '2222', "creditos": 5, "semestre": 7, "prelaciones": ['2217', '2507'] },
            { "id": 1035, "nombre": 'Sistemas de Potencia I', "codigo": '2345', "creditos": 3, "semestre": 7, "prelaciones": ['2109'] },
            { "id": 1036, "nombre": 'Comunicaciones I', "codigo": '2426', "creditos": 5, "semestre": 7, "prelaciones": ['2109', '2415'] },
            { "id": 1037, "nombre": 'Conversión de Energía', "codigo": '2132', "creditos": 3, "semestre": 7, "prelaciones": ['0441', '0602', '2124'] },
            { "id": 1038, "nombre": 'Sistemas Digitales I', "codigo": '2234', "creditos": 3, "semestre": 7, "prelaciones": ['2217', '2233'] },
            { "id": 1039, "nombre": 'Comunicaciones II', "codigo": '2427', "creditos": 4, "semestre": 8, "prelaciones": ['2426'] },
            { "id": 1040, "nombre": 'Ondas Guiadas', "codigo": '2440', "creditos": 4, "semestre": 8, "prelaciones": ['2124', '2426'] },
            { "id": 1041, "nombre": 'Propagación y Antenas', "codigo": '2441', "creditos": 5, "semestre": 8, "prelaciones": ['2124', '2426'] },
            { "id": 1042, "nombre": 'Lab. de Comunicaciones I', "codigo": '2428', "creditos": 2, "semestre": 8, "prelaciones": ['2216', '2426'] },
            { "id": 1043, "nombre": 'Sistema de Telecomunicaciones II', "codigo": '2416', "creditos": 4, "semestre": 8, "prelaciones": ['2426'] },
            { "id": 1044, "nombre": 'Electiva', "codigo": 'EEC-1', "creditos": 4, "semestre": 9, "prelaciones": [{"tipo": 'creditos', "valor": 150}] },
            { "id": 1045, "nombre": 'Trabajo de Grado I', "codigo": '2483', "creditos": 4, "semestre": 9, "prelaciones": [{"tipo": 'creditos', "valor": 150}] },
            { "id": 1046, "nombre": 'Sistema de Telecomunicaciones III', "codigo": '2417', "creditos": 4, "semestre": 9, "prelaciones": ['2416', '2441'] },
            { "id": 1047, "nombre": 'Lab. de Comunicaciones II', "codigo": '2429', "creditos": 1, "semestre": 9, "prelaciones": ['2428', '2440'] },
            { "id": 1048, "nombre": 'Ejercicio Profesional y Gerencia', "codigo": '2520', "creditos": 4, "semestre": 9, "prelaciones": [{"tipo": 'creditos', "valor": 130}] },
            { "id": 1049, "nombre": 'Electiva', "codigo": 'EEC-2', "creditos": 4, "semestre": 10, "prelaciones": [{"tipo": 'creditos', "valor": 150}] },
            { "id": 1050, "nombre": 'Electiva', "codigo": 'EEC-3', "creditos": 4, "semestre": 10, "prelaciones": [{"tipo": 'creditos', "valor": 150}] },
            { "id": 1051, "nombre": 'Trabajo de Grado II', "codigo": '2484', "creditos": 9, "semestre": 10, "prelaciones": ['2483'] },
            { "id": 1052, "nombre": 'Ingeniería Económica', "codigo": '2523', "creditos": 4, "semestre": 10, "prelaciones": ['2520'] }
        ]
    }
};
